### ISSUE TITLE
If possible, it is recommended to add the DoH function. Thanks！

### ISSUE THREAD

**Issue by viagram** [mosajjal/sniproxy#32]
If possible, it is recommended to add the DoH function.Thanks！
You can refer to: [dns-over-https](https://github.com/m13253/dns-over-https)

**Comment by mosajjal** [comment]
we do have doh in both server and client mode. what specifically do you need?

**Comment by viagram** [comment]
I want to provide DoH service on the server side, but I can't find a way to enable it. In your config sample file "config.sample.json" only find `"bindDnsOverTcp": false,
     "bindDnsOverTls": false,
     "bindDnsOverQuic": false,
     "tlsCert": "",
     "tlsKey": "",`
The relevant parameters of bindDnsOverDoH were not found, for example:
` "bindDnsOverDoH": true,
"dohPort": 9443,
"dohPath": "/dns-query",`
And the function runDNS () did not find the relevant code to enable DoH, please advise, thank you!

**Comment by mosajjal** [comment]
with the reverse proxy function, I reckon we can do this now. but it'll make the code even more complex than it is today. let me see what I can do from my side to re-architecture the HTTPS side. I'll keep this issue open.

**Comment by viagram** [comment]
Well, looking forward to your excellent finished product.

**Comment by viagram** [comment]
> with the reverse proxy function, I reckon we can do this now. but it'll make the code even more complex than it is today. let me see what I can do from my side to re-architecture the HTTPS side. I'll keep this issue open.
The reverse proxy does not seem to support the original sni function of the program?

**Comment by viagram** [comment]
> with the reverse proxy function, I reckon we can do this now. but it'll make the code even more complex than it is today. let me see what I can do from my side to re-architecture the HTTPS side. I'll keep this issue open.

The reverse proxy does not seem to support the original sni function of the program?

**Comment by mosajjal** [comment]
at the moment my recommendation is to use [this project](https://github.com/m13253/dns-over-https) as a DoH server and configure `sniproxy` to use it as reverse proxy. for example:


let's assume your server IP is `111.111.111.111` and you have a domain `mydns.tk` pointing to it 

step 1) run a DoH server on a random port:

``` 
docker run -d --name doh-server \
  -p 8053:8053 \
  -e UPSTREAM_DNS_SERVER="udp:111.111.111.111:53" \
  -e DOH_HTTP_PREFIX="/dns-query" \
  -e DOH_SERVER_LISTEN=":8053" \
  -e DOH_SERVER_TIMEOUT="10" \
  -e DOH_SERVER_TRIES="3" \
  -e DOH_SERVER_VERBOSE="false" \
  satishweb/doh-server
```

above will listen on port 8053 and exposes a DoH server with the upstream of sniproxy's UDP provider on port 53. 

step 2) get a certificate for `mydns.tk` and place it under `/opt/sniproxy/cert.crt` and `/opt/sniproxy/cert.key`

step 3) run `sniproxy` with these options:

```
/opt/sniproxy/sniproxy --[redacted options]... --reverseProxyCert=/opt/sniproxy/cert.crt --reverseProxyKey=/opt/sniproxy/cert.key --reverseProxy=mydns.tk::http://127.0.0.1:8853
```

this should provide a DoH function on port `443` and the rest of sniproxy will remain unaffected since the DoH server goes back to `sniproxy` for DNS functionality. 

let me know if this works. haven't tested it myself.

**Comment by viagram** [comment]
The main thing is to implement the sni function while supporting DoH. Reverse proxy does not have this option. But thank you for your patient answer.

**Comment by mosajjal** [comment]
by configuring the DoH server to have `sniproxy`'s builtin DNS as upstream, you'll maintain all the functionality.

**Comment by viagram** [comment]
Thanks
