### ISSUE TITLE
does sniproxy can proxy ports other than 80 and 443?

### ISSUE THREAD

**Issue by cloudslsw** [mosajjal/sniproxy#79]
17:41:25 flag=0 connectlog:HotSpot: DNS resolve: s0.xbox.wfb.gmru.net from DNS, IP:95.163.33.227
17:41:25 flag=0 connectlog:HotSpot: Connect to s0.xbox.wfb.gmru.net:5229 success...

this is a connection log from gaming vpn from PC, and the pc share connection to my xbox one, with pc shared connection i can play games online on my xbox console, but with hosts on router and sniproxy i cant connect games online on my xbox console,  i dont know why but i seen this game use port 5229, does sniproxy can proxy this port?

**Comment by mosajjal** [comment]
currently, `443` and `80` are both hard-coded into `sniproxy` and if the TLS connection is hitting another port other than standard ones, `sniproxy` will still try to connect via 443 rather than the correct port. I have no plans on reworking `sniproxy` to answer to incoming TCP connections from ALL ports, but happy to take a PR.
